<a href="https://colab.research.google.com/github/nandeeswarbadugu/Pytorch/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch


# Create random tensor
tensorA = torch.rand(size = (7, 7))
tensorA


tensor([[0.3805, 0.6595, 0.9005, 0.2659, 0.0402, 0.3279, 0.4664],
        [0.9283, 0.3946, 0.5643, 0.9954, 0.6762, 0.3672, 0.3355],
        [0.0552, 0.2285, 0.1885, 0.3464, 0.1299, 0.6027, 0.8855],
        [0.4611, 0.4396, 0.7503, 0.3520, 0.7308, 0.0934, 0.9558],
        [0.8831, 0.8801, 0.5270, 0.1419, 0.9269, 0.2062, 0.4067],
        [0.8262, 0.0690, 0.0742, 0.3434, 0.6464, 0.5721, 0.9538],
        [0.5294, 0.7523, 0.2863, 0.9148, 0.9787, 0.7918, 0.4815]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensorB = torch.rand(size = (1, 7))
# Perform matrix multiplication
tensorC = torch.matmul(tensorA, tensorB.T)
tensorC


tensor([[1.0618],
        [1.0711],
        [0.9940],
        [1.3530],
        [0.8871],
        [1.0866],
        [1.1153]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensorD = torch.rand(size = (7, 7))

tensorE = torch.rand(size = (1, 7))
# Perform matrix multiplication

# Matrix multiply tensors
tensorF = torch.matmul(tensorD, tensorE.T)
tensorF

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



1949387749238117058


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU

tensor_1 = torch.rand(2,3).to(device)


tensor_2 = torch.rand(2,3).to(device)

print(f"{tensor_1} \n {tensor_2}")



tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') 
 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [10]:
# Perform matmul on tensor_A and tensor_B
tensor_3 = torch.matmul(tensor_1, tensor_2.T)
print(f"{tensor_3} {tensor_3.shape}")


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [11]:
# Find max
print(f"Max value is : {tensor_3.max()}")

# Find min
print(f"Min value is : {tensor_3.min()}")

Max value is : 0.5617256760597229
Min value is : 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [12]:
# Find arg max
print(f"Position of Max value is : {tensor_3.argmax()}")

# Find arg min
print(f"Position of Min value is : {tensor_3.argmin()}")

Position of Max value is : 3
Position of Min value is : 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [16]:
# Set seed
torch.manual_seed(7)

# Create random tensor

tensor_4 = torch.rand(size = (1, 1, 1, 10))
print(f"{tensor_4} {tensor_4.shape}")

# Remove single dimensions
tensor_5 = tensor_4.squeeze()


# Print out tensors and their shapes

print(f"{tensor_5} {tensor_5.shape}")

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
