<a href="https://colab.research.google.com/github/nandeeswarbadugu/Pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# New Section

In [2]:
# Scalar
scalar = torch.tensor(8)
scalar
scalar.ndim
# Scalar is zero dimension
# to create tensor use torch.tensor
# to extract data from tesnor scalar.item()


0

In [3]:
scalar.item()

8

In [4]:
# vectors
vector = torch.tensor([7, 7,8])
vector

tensor([7, 7, 8])

In [5]:
vector.ndim
# dimension is always 1 for vector
vector.shape
# shape will be number of elements

torch.Size([3])

In [6]:
# Matrix
MATRIX = torch.tensor([[1,2,5], [3,4,6], [5,6,7]])
MATRIX

tensor([[1, 2, 5],
        [3, 4, 6],
        [5, 6, 7]])

In [7]:
MATRIX.ndim
# matrix is always two dimensional

2

In [8]:
MATRIX.shape
# three rows three comlums
# dim 0 rows
# dim 1 columns

torch.Size([3, 3])

In [9]:
TENSOR = torch.tensor( [[[1,2,3,6],[4,5,6,10],[10,11,12,13],[10,11,12,13]]])
TENSOR

tensor([[[ 1,  2,  3,  6],
         [ 4,  5,  6, 10],
         [10, 11, 12, 13],
         [10, 11, 12, 13]]])

In [10]:
TENSOR.ndim

3

In [11]:
TENSOR.shape

torch.Size([1, 4, 4])

Random tensors¶
We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [12]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.5500, 0.3425, 0.9585, 0.2115],
        [0.7273, 0.3432, 0.9319, 0.0975],
        [0.9207, 0.6666, 0.7001, 0.7452]])

In [13]:
 random_tensor.ndim

2

In [14]:
# random tensor with zeros
zero_tensor = torch.zeros(size=(5,10,4))
zero_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 

In [15]:
ones_tensor = torch.ones(size=(5,10,4))
ones_tensor
ones_tensor.dtype

torch.float32

In [16]:
range_tensor = torch.arange(start=0, end=1000, step=77)
range_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [17]:
range_tensor = torch.arange(start=0, end=11, step=0.5)
range_tensor

tensor([ 0.0000,  0.5000,  1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,
         4.0000,  4.5000,  5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,
         8.0000,  8.5000,  9.0000,  9.5000, 10.0000, 10.5000])

In [18]:
# tesnor types by default tensor type is float32
range_tensor.dtype

torch.float32

In [19]:
float_32_tensor = torch.tensor([3.0,5.0,6.0],
                               dtype=torch.float16,
                               device = "cuda",
                               requires_grad=True)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float16, device(type='cuda', index=0))

In [20]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [21]:
# torch.cuda.is_available()
!nvidia-smi
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

Sun Jul 13 16:30:09 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P0             26W /   70W |     104MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [22]:
zero_tensor = torch.zeros(size = (10,3,4))
zero_tensor
# First dimension has ten elements
# each element is an 3 * 4 Matrix

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
ones_tensor = torch.ones(size= (10,3,4))
ones_tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [24]:
random_tensor = torch.rand(size = (10,3,4))
random_tensor

tensor([[[0.1044, 0.6580, 0.8729, 0.8911],
         [0.4371, 0.5015, 0.7802, 0.7802],
         [0.0821, 0.6996, 0.5401, 0.8142]],

        [[0.1367, 0.8302, 0.4475, 0.0057],
         [0.7296, 0.4847, 0.6668, 0.7815],
         [0.5607, 0.3958, 0.3359, 0.3765]],

        [[0.1804, 0.4851, 0.1292, 0.0619],
         [0.0364, 0.0207, 0.7181, 0.2035],
         [0.1868, 0.7044, 0.0914, 0.1440]],

        [[0.6851, 0.7362, 0.1744, 0.7456],
         [0.8773, 0.7679, 0.2704, 0.0759],
         [0.6953, 0.9645, 0.5462, 0.9114]],

        [[0.0082, 0.3694, 0.2776, 0.4779],
         [0.8127, 0.7869, 0.9356, 0.7647],
         [0.7274, 0.2508, 0.0981, 0.7761]],

        [[0.6112, 0.5152, 0.2720, 0.1441],
         [0.5173, 0.2378, 0.5759, 0.5080],
         [0.9643, 0.8303, 0.3439, 0.8614]],

        [[0.0584, 0.0061, 0.1498, 0.4484],
         [0.6032, 0.2874, 0.0781, 0.7471],
         [0.5498, 0.3563, 0.3943, 0.8765]],

        [[0.7056, 0.1411, 0.6433, 0.2054],
         [0.5695, 0.8176, 0.8310, 0.8109

In [25]:
range_tensor = torch.arange(0, 60, 0.5).view(10,3,4)
range_tensor

tensor([[[ 0.0000,  0.5000,  1.0000,  1.5000],
         [ 2.0000,  2.5000,  3.0000,  3.5000],
         [ 4.0000,  4.5000,  5.0000,  5.5000]],

        [[ 6.0000,  6.5000,  7.0000,  7.5000],
         [ 8.0000,  8.5000,  9.0000,  9.5000],
         [10.0000, 10.5000, 11.0000, 11.5000]],

        [[12.0000, 12.5000, 13.0000, 13.5000],
         [14.0000, 14.5000, 15.0000, 15.5000],
         [16.0000, 16.5000, 17.0000, 17.5000]],

        [[18.0000, 18.5000, 19.0000, 19.5000],
         [20.0000, 20.5000, 21.0000, 21.5000],
         [22.0000, 22.5000, 23.0000, 23.5000]],

        [[24.0000, 24.5000, 25.0000, 25.5000],
         [26.0000, 26.5000, 27.0000, 27.5000],
         [28.0000, 28.5000, 29.0000, 29.5000]],

        [[30.0000, 30.5000, 31.0000, 31.5000],
         [32.0000, 32.5000, 33.0000, 33.5000],
         [34.0000, 34.5000, 35.0000, 35.5000]],

        [[36.0000, 36.5000, 37.0000, 37.5000],
         [38.0000, 38.5000, 39.0000, 39.5000],
         [40.0000, 40.5000, 41.0000, 41.5000]],


Matrix multiplication cond is number of cols in 1st matrix = number of rows in second matrix

3 * 2     2  *. 2
    -     -

resultant matrix is 3 * 2

In [26]:
TENSOR_A = torch.rand(size = (3,2))

In [27]:
TENSOR_B = torch.rand(size = (2,2))
TENSOR_B

tensor([[0.6657, 0.0915],
        [0.5333, 0.3170]])

In [28]:
RES_TENSOR = torch.matmul(TENSOR_A, TENSOR_B)
RES_TENSOR

tensor([[1.0534, 0.3440],
        [0.3938, 0.1831],
        [0.6265, 0.2302]])

In [29]:
TENSOR_B = torch.rand(size = (3,2))
TENSOR_B
# transpose matrix
TENSOR_B.T

tensor([[0.8794, 0.6141, 0.6879],
        [0.4278, 0.6044, 0.4314]])

Neural networks are full of matrix multiplications and dot products.

The torch.nn.Linear() module (we'll see this in action later on), also known as a **feed-forward layer or fully connected layer**, implements a matrix multiplication between an input x and a weights matrix A.

$$ y = x\cdot{A^T} + b $$

In [46]:
torch.manual_seed(45)
linear = torch.nn.Linear(in_features = 3, out_features = 6)
print(f"Linear: {linear.weight}")
x = torch.zeros(size = (3,3))
print(f"x matrix is :{x}")
output = linear(x)
print(f"input shape: {x.shape}")
print(f"output:\n {output}\n\noutput shape: {output.shape}")

# y = mx + b
# 3 * 3 mul 3 * 6


Linear: Parameter containing:
tensor([[-0.3615,  0.5327,  0.2118],
        [ 0.4605, -0.5190,  0.0640],
        [ 0.3304, -0.5120,  0.3282],
        [-0.4065, -0.5325, -0.4576],
        [-0.0905, -0.3033,  0.3592],
        [ 0.0393,  0.2118,  0.1765]], requires_grad=True)
x matrix is :tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
input shape: torch.Size([3, 3])
output:
 tensor([[ 0.1296,  0.5581, -0.3665, -0.4343, -0.0852,  0.5446],
        [ 0.1296,  0.5581, -0.3665, -0.4343, -0.0852,  0.5446],
        [ 0.1296,  0.5581, -0.3665, -0.4343, -0.0852,  0.5446]],
       grad_fn=<AddmmBackward0>)

output shape: torch.Size([3, 6])


✅ What the Linear Layer Does
A PyTorch nn.Linear(in_features, out_features) layer performs this operation:

output
=
𝑥
⋅
𝑊
𝑇
+
𝑏
output=x⋅W
T
 +b
Where:

𝑥
x is your input (shape: [batch_size, in_features])

𝑊
W is the weight matrix (shape: [out_features, in_features])

𝑏
b is the bias vector (shape: [out_features])

𝑊
𝑇
W
T
  is the transpose of weights (shape: [in_features, out_features]), so the matmul x @ W^T gives output of shape [batch_size, out_features]
  x is of zize 3 * 3
weight matrix is of size 6 * 3
it get's transposed so 3 * 6
output will be x @ linear.T
3 * 6


In [42]:
# how to make two random tensors equal
# this can be done using manual seed
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[-0.3615,  0.5327,  0.2118],
        [ 0.4605, -0.5190,  0.0640],
        [ 0.3304, -0.5120,  0.3282],
        [-0.4065, -0.5325, -0.4576],
        [-0.0905, -0.3033,  0.3592],
        [ 0.0393,  0.2118,  0.1765]], requires_grad=True)
Parameter containing:
tensor([ 0.1296,  0.5581, -0.3665, -0.4343, -0.0852,  0.5446],
       requires_grad=True)


In [52]:
# Create a tensor
x = torch.arange(0, 100, 10)
print(f"x is : {x}")

print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float).mean()}")
print(f"Sum: {x.sum()}")

x is : tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [53]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [54]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


Data type manipulation

In [57]:
# Create two tensor with type float32 and float 16
tensor = torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

You can change the datatypes of tensors using torch.Tensor.type(dtype=None) where the dtype parameter is the datatype you'd like to use.

In [60]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [59]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)