<a href="https://colab.research.google.com/github/nandeeswarbadugu/Pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# New Section

In [ ]:
# Scalar
scalar = torch.tensor(8)
scalar
scalar.ndim
# Scalar is zero dimension
# to create tensor use torch.tensor
# to extract data from tesnor scalar.item()


0

In [ ]:
scalar.item()

8

In [ ]:
# vectors
vector = torch.tensor([7, 7,8])
vector

tensor([7, 7, 8])

In [ ]:
vector.ndim
# dimension is always 1 for vector
vector.shape
# shape will be number of elements

torch.Size([3])

In [ ]:
# Matrix
MATRIX = torch.tensor([[1,2,5], [3,4,6], [5,6,7]])
MATRIX

tensor([[1, 2, 5],
        [3, 4, 6],
        [5, 6, 7]])

In [ ]:
MATRIX.ndim
# matrix is always two dimensional

2

In [ ]:
MATRIX.shape
# three rows three comlums
# dim 0 rows
# dim 1 columns

torch.Size([3, 3])

In [ ]:
TENSOR = torch.tensor( [[[1,2,3,6],[4,5,6,10],[10,11,12,13],[10,11,12,13]]])
TENSOR

tensor([[[ 1,  2,  3,  6],
         [ 4,  5,  6, 10],
         [10, 11, 12, 13],
         [10, 11, 12, 13]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 4, 4])

Random tensors¶
We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [ ]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.1163, 0.9475, 0.3892, 0.3870],
        [0.6688, 0.6228, 0.7319, 0.7502],
        [0.2852, 0.6291, 0.1472, 0.0088]])

In [ ]:
 random_tensor.ndim

2

In [ ]:
# random tensor with zeros
zero_tensor = torch.zeros(size=(5,10,4))
zero_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 

In [ ]:
ones_tensor = torch.ones(size=(5,10,4))
ones_tensor
ones_tensor.dtype

torch.float32

In [ ]:
range_tensor = torch.arange(start=0, end=1000, step=77)
range_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
range_tensor = torch.arange(start=0, end=11, step=0.5)
range_tensor

tensor([ 0.0000,  0.5000,  1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,
         4.0000,  4.5000,  5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,
         8.0000,  8.5000,  9.0000,  9.5000, 10.0000, 10.5000])

In [ ]:
# tesnor types by default tensor type is float32
range_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0,5.0,6.0],
                               dtype=torch.float16,
                               device = "cuda",
                               requires_grad=True)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float16, device(type='cuda', index=0))

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))