<a href="https://colab.research.google.com/github/nandeeswarbadugu/Pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# New Section

In [16]:
# Scalar
scalar = torch.tensor(8)
scalar
scalar.ndim
# Scalar is zero dimension
# to create tensor use torch.tensor
# to extract data from tesnor scalar.item()


0

In [17]:
scalar.item()

8

In [18]:
# vectors
vector = torch.tensor([7, 7,8])
vector

tensor([7, 7, 8])

In [19]:
vector.ndim
# dimension is always 1 for vector
vector.shape
# shape will be number of elements

torch.Size([3])

In [20]:
# Matrix
MATRIX = torch.tensor([[1,2,5], [3,4,6], [5,6,7]])
MATRIX

tensor([[1, 2, 5],
        [3, 4, 6],
        [5, 6, 7]])

In [21]:
MATRIX.ndim
# matrix is always two dimensional

2

In [22]:
MATRIX.shape
# three rows three comlums
# dim 0 rows
# dim 1 columns

torch.Size([3, 3])

In [23]:
TENSOR = torch.tensor( [[1,2,3,6],[4,5,6,10],[10,11,12,13],[10,11,12,13]]])
TENSOR

tensor([[[ 1,  2,  3,  6],
         [ 4,  5,  6, 10],
         [10, 11, 12, 13],
         [10, 11, 12, 13]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR.shape

torch.Size([1, 4, 4])