<a href="https://colab.research.google.com/github/nandeeswarbadugu/Pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# New Section

In [3]:
# Scalar
scalar = torch.tensor(8)
scalar
scalar.ndim
# Scalar is zero dimension
# to create tensor use torch.tensor
# to extract data from tesnor scalar.item()


0

In [4]:
scalar.item()

8

In [5]:
# vectors
vector = torch.tensor([7, 7,8])
vector

tensor([7, 7, 8])

In [6]:
vector.ndim
# dimension is always 1 for vector
vector.shape
# shape will be number of elements

torch.Size([3])

In [7]:
# Matrix
MATRIX = torch.tensor([[1,2,5], [3,4,6], [5,6,7]])
MATRIX

tensor([[1, 2, 5],
        [3, 4, 6],
        [5, 6, 7]])

In [8]:
MATRIX.ndim
# matrix is always two dimensional

2

In [9]:
MATRIX.shape
# three rows three comlums
# dim 0 rows
# dim 1 columns

torch.Size([3, 3])

In [10]:
TENSOR = torch.tensor( [[[1,2,3,6],[4,5,6,10],[10,11,12,13],[10,11,12,13]]])
TENSOR

tensor([[[ 1,  2,  3,  6],
         [ 4,  5,  6, 10],
         [10, 11, 12, 13],
         [10, 11, 12, 13]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 4, 4])

Random tensors¶
We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [13]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.8897, 0.1644, 0.9353, 0.1430],
        [0.6426, 0.0950, 0.3038, 0.9239],
        [0.7522, 0.5699, 0.2034, 0.7818]])

In [14]:
 random_tensor.ndim

2

In [15]:
# random tensor with zeros
zero_tensor = torch.zeros(size=(5,10,4))
zero_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 

In [16]:
ones_tensor = torch.ones(size=(5,10,4))
ones_tensor
ones_tensor.dtype

torch.float32

In [17]:
range_tensor = torch.arange(start=0, end=1000, step=77)
range_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [18]:
range_tensor = torch.arange(start=0, end=11, step=0.5)
range_tensor

tensor([ 0.0000,  0.5000,  1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,
         4.0000,  4.5000,  5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,
         8.0000,  8.5000,  9.0000,  9.5000, 10.0000, 10.5000])

In [19]:
# tesnor types by default tensor type is float32
range_tensor.dtype

torch.float32

In [20]:
float_32_tensor = torch.tensor([3.0,5.0,6.0],
                               dtype=torch.float16,
                               device = "cuda",
                               requires_grad=True)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float16, device(type='cuda', index=0))

In [21]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [22]:
# torch.cuda.is_available()
!nvidia-smi
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

Sun Jul 13 02:47:50 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   57C    P0             28W /   70W |     104MiB /  15360MiB |      2%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [23]:
zero_tensor = torch.zeros(size = (10,3,4))
zero_tensor
# First dimension has ten elements
# each element is an 3 * 4 Matrix

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
ones_tensor = torch.ones(size= (10,3,4))
ones_tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [25]:
random_tensor = torch.rand(size = (10,3,4))
random_tensor

tensor([[[0.5151, 0.5344, 0.8901, 0.7217],
         [0.0404, 0.2564, 0.4017, 0.6327],
         [0.1264, 0.5116, 0.2104, 0.7844]],

        [[0.5719, 0.7780, 0.2958, 0.4816],
         [0.9942, 0.6179, 0.7441, 0.5448],
         [0.1211, 0.8566, 0.8610, 0.6453]],

        [[0.0824, 0.2841, 0.4838, 0.7480],
         [0.7902, 0.3076, 0.7095, 0.1941],
         [0.1656, 0.6830, 0.0611, 0.4010]],

        [[0.0436, 0.0457, 0.0417, 0.3272],
         [0.7930, 0.1632, 0.8661, 0.6238],
         [0.4133, 0.0768, 0.6893, 0.7394]],

        [[0.4881, 0.4635, 0.9430, 0.2086],
         [0.7912, 0.3872, 0.8790, 0.1512],
         [0.0579, 0.9943, 0.6181, 0.0505]],

        [[0.2691, 0.9782, 0.5451, 0.8362],
         [0.1591, 0.1695, 0.8130, 0.6426],
         [0.3649, 0.9468, 0.7881, 0.8864]],

        [[0.0171, 0.6993, 0.0567, 0.2261],
         [0.0225, 0.0640, 0.9453, 0.5887],
         [0.1512, 0.0677, 0.2798, 0.0914]],

        [[0.2937, 0.7146, 0.4207, 0.9048],
         [0.0811, 0.7682, 0.2411, 0.4152

In [26]:
range_tensor = torch.arange(0, 60, 0.5).view(10,3,4)
range_tensor

tensor([[[ 0.0000,  0.5000,  1.0000,  1.5000],
         [ 2.0000,  2.5000,  3.0000,  3.5000],
         [ 4.0000,  4.5000,  5.0000,  5.5000]],

        [[ 6.0000,  6.5000,  7.0000,  7.5000],
         [ 8.0000,  8.5000,  9.0000,  9.5000],
         [10.0000, 10.5000, 11.0000, 11.5000]],

        [[12.0000, 12.5000, 13.0000, 13.5000],
         [14.0000, 14.5000, 15.0000, 15.5000],
         [16.0000, 16.5000, 17.0000, 17.5000]],

        [[18.0000, 18.5000, 19.0000, 19.5000],
         [20.0000, 20.5000, 21.0000, 21.5000],
         [22.0000, 22.5000, 23.0000, 23.5000]],

        [[24.0000, 24.5000, 25.0000, 25.5000],
         [26.0000, 26.5000, 27.0000, 27.5000],
         [28.0000, 28.5000, 29.0000, 29.5000]],

        [[30.0000, 30.5000, 31.0000, 31.5000],
         [32.0000, 32.5000, 33.0000, 33.5000],
         [34.0000, 34.5000, 35.0000, 35.5000]],

        [[36.0000, 36.5000, 37.0000, 37.5000],
         [38.0000, 38.5000, 39.0000, 39.5000],
         [40.0000, 40.5000, 41.0000, 41.5000]],


Matrix multiplication cond is number of cols in 1st matrix = number of rows in second matrix

3 * 2     2  *. 2
    -     -

resultant matrix is 3 * 2

In [33]:
TENSOR_A = torch.rand(size = (3,2))

In [32]:
TENSOR_B = torch.rand(size = (2,2))
TENSOR_B

tensor([[0.5212, 0.0738],
        [0.9320, 0.1721]])

In [34]:
RES_TENSOR = torch.matmul(TENSOR_A, TENSOR_B)
RES_TENSOR

tensor([[0.9391, 0.1613],
        [0.8785, 0.1411],
        [0.8832, 0.1578]])

In [37]:
TENSOR_B = torch.rand(size = (3,2))
TENSOR_B
# transpose matrix
TENSOR_B.T

tensor([[0.0207, 0.2994, 0.8189],
        [0.3299, 0.9324, 0.1468]])